# Add configuration values here, as shown below.
#
GMAIL_USERNAME:  "timetoeat16@gmail.com"
GMAIL_PASSWORD: ""
GMAIL_DOMAIN: "gmail.com"

# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
