# Add configuration values here, as shown below.
#
GMAIL_USERNAME:  "timetoeat16@gmail.com"
GMAIL_PASSWORD: "lala1234567"
GMAIL_DOMAIN: "gmail.com"

# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

YELP_CONSUMER_KEY: "zb5mQSzZKN768S3f-X4L6w"
YELP_CONSUMER_SECRET: "_4nZaqMoHsv7BW02ubO4o5GFy0Y"
YELP_TOKEN: "muAIIMmCq5__wBVhxOqr3nI5s_xwOY6e"
YELP_TOKEN_SECRET: "UXhCeoPWf0AF-pSYI9r_XKFcNSM"